"""Generate enhanced bilingual EDA reports and figures from analysis tables.

Run after:
    /opt/miniconda3/bin/python src/proximity_data_analysis/02_eda_uwa_mating_analysis.py

Then run:
    /opt/miniconda3/bin/python src/proximity_data_analysis/03_eda_report_generation.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
from matplotlib.lines import Line2D


EDA_DIR = Path("data/uwa_proximity_eda")
TABLE_DIR = EDA_DIR / "tables"
FIG_DIR = EDA_DIR / "figures"
REPORT_DIR = EDA_DIR / "reports"

YEARS = [2023, 2024]
TREATMENT_ORDER = ["High_shade", "Medium_shade", "No_shade"]

YEAR_COLORS = {2023: "#1f77b4", 2024: "#ff7f0e"}
CLASS_COLORS = {
    "selected": "#2a9d8f",
    "candidate_not_selected": "#e76f51",
    "non_candidate": "#8ecae6",
}


def save_figure(fig: plt.Figure, out_path: Path) -> None:
    """Save figure with extra padding to avoid clipping legends/annotations."""
    fig.savefig(out_path, bbox_inches="tight", pad_inches=0.25)


def ensure_dirs() -> None:
    """Create report folders if missing."""
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)


def require_tables() -> Dict[str, pd.DataFrame]:
    """Load required CSV tables generated by analysis pipeline."""
    required = {
        "parameters": "analysis_parameters.csv",
        "prefilter_audit": "pair_prefilter_audit.csv",
        "prefilter_summary": "prefilter_summary.csv",
        "pair_metrics": "pair_signal_metrics.csv",
        "pair_event_summary": "pair_event_summary.csv",
        "anomaly": "plot_day_anomaly_metrics.csv",
        "split_index": "final_result_file_index.csv",
        "final_results": "mating_results_all.csv",
        "ram_day": "ram_day.csv",
        "ewe_summary": "ewe_summary.csv",
        "tz_summary": "tz_summary.csv",
    }

    loaded: Dict[str, pd.DataFrame] = {}
    for key, name in required.items():
        p = TABLE_DIR / name
        if not p.exists():
            raise FileNotFoundError(f"Missing required table: {p}")
        loaded[key] = pd.read_csv(p)

    return loaded


def param_map(df: pd.DataFrame) -> Dict[str, float]:
    """Convert parameter table to a key-value mapping."""
    out: Dict[str, float] = {}
    for _, row in df.iterrows():
        out[str(row["parameter"])] = float(row["value"])
    return out


def fmt_pct(numerator: float, denominator: float) -> str:
    """Format percentage with one decimal place."""
    if denominator == 0:
        return "0.0%"
    return f"{100.0 * numerator / denominator:.1f}%"


def fmt_num(value: float) -> str:
    """Format numeric parameter without unintended integer rounding."""
    if float(value).is_integer():
        return str(int(value))
    return f"{value:.3f}".rstrip("0").rstrip(".")


def df_to_markdown(df: pd.DataFrame, max_rows: int = 20) -> str:
    """Render table to markdown with fallback if tabulate is unavailable."""
    show = df.head(max_rows).copy()
    try:
        return show.to_markdown(index=False)
    except Exception:
        return "```\n" + show.to_string(index=False) + "\n```"


def preprocess_tables(tables: Dict[str, pd.DataFrame]) -> None:
    """Apply common datatype normalization for plotting and reporting."""
    tables["anomaly"]["date"] = pd.to_datetime(tables["anomaly"]["date"])
    tables["anomaly"]["management_anomaly"] = tables["anomaly"]["management_anomaly"].astype(bool)

    tables["final_results"]["is_mating"] = tables["final_results"]["Mating"].eq("Y")
    tables["final_results"]["date"] = pd.to_datetime(tables["final_results"]["date"], errors="coerce")

    if "year" in tables["ram_day"].columns:
        tables["ram_day"]["year"] = tables["ram_day"]["year"].astype(int)
    if "year" in tables["ewe_summary"].columns:
        tables["ewe_summary"]["year"] = tables["ewe_summary"]["year"].astype(int)
    if "year" in tables["tz_summary"].columns:
        tables["tz_summary"]["year"] = tables["tz_summary"]["year"].astype(int)


# -----------------------------
# Figure generation
# -----------------------------

def plot_prefilter_evidence(prefilter_audit: pd.DataFrame, prefilter_summary: pd.DataFrame, params: Dict[str, float]) -> str:
    """Plot evidence for pair-level pre-filter behavior."""
    fig, axes = plt.subplots(1, 2, figsize=(16, 5), constrained_layout=True)

    # Left: non-zero day distribution.
    non_zero_days = prefilter_audit["non_zero_days"].fillna(0)
    axes[0].hist(non_zero_days, bins=range(0, int(non_zero_days.max()) + 2), color="#4c78a8", alpha=0.85)
    axes[0].axvline(params["PAIR_MIN_NONZERO_DAYS"], color="#f58518", linestyle="--", linewidth=2, label="Step2 threshold")
    axes[0].set_title("Pair Non-zero Day Distribution")
    axes[0].set_xlabel("Non-zero days in full experiment window")
    axes[0].set_ylabel("Pair count")
    axes[0].legend(loc="upper right", frameon=True)

    # Right: pre-filter outcome by group.
    summary = prefilter_summary.copy()
    summary["year_treat"] = summary["year"].astype(str) + "-" + summary["treatment"]
    x = np.arange(len(summary))

    removed_step2 = summary["removed_step2_nonzero_lt7"].to_numpy()
    removed_step4 = summary["removed_step4_robust_z"].to_numpy()
    kept = summary["kept_pairs"].to_numpy()

    axes[1].bar(x, removed_step2, color="#e45756", label="Removed by Step2 (<7 days)")
    axes[1].bar(x, removed_step4, bottom=removed_step2, color="#f58518", label="Removed by Step4 (|rz|>3)")
    axes[1].bar(x, kept, bottom=removed_step2 + removed_step4, color="#54a24b", label="Kept")
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(summary["year_treat"], rotation=30, ha="right")
    axes[1].set_ylabel("Pair count")
    axes[1].set_title("Pre-filter Flow by Year-Treatment")
    axes[1].legend(loc="upper left", bbox_to_anchor=(1.02, 1.0), borderaxespad=0.0, frameon=True)

    out = FIG_DIR / "01_prefilter_evidence.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


def _plot_year_anomaly_panel(anomaly: pd.DataFrame, year: int) -> str:
    """Plot robust-z anomaly panel for one year."""
    sub = anomaly[anomaly["year"] == year].copy()
    fig, axes = plt.subplots(2, 3, figsize=(22, 9), sharex=False)
    fig.subplots_adjust(top=0.88, bottom=0.14, left=0.055, right=0.84, wspace=0.22, hspace=0.24)

    for col_idx, treatment in enumerate(TREATMENT_ORDER):
        g = sub[sub["treatment"] == treatment].sort_values("date")
        if g.empty:
            axes[0, col_idx].set_axis_off()
            axes[1, col_idx].set_axis_off()
            continue

        x = g["date"]
        flags = g["management_anomaly"]

        axes[0, col_idx].plot(x, g["rz_total"], color="#1f77b4", marker="o", linewidth=1.8, label="rz_total")
        axes[0, col_idx].scatter(x[flags], g.loc[flags, "rz_total"], color="#d62728", s=45, label="Flagged day")
        axes[0, col_idx].axhline(3.0, color="#f58518", linestyle="--", linewidth=1.4, label="Threshold +3")
        axes[0, col_idx].set_title(f"{treatment} | rz_total", pad=10)
        axes[0, col_idx].set_ylabel("Robust z-score")
        axes[0, col_idx].tick_params(axis="x", labelbottom=False)

        axes[1, col_idx].plot(x, g["rz_sync"], color="#2ca02c", marker="s", linewidth=1.8, label="rz_sync")
        axes[1, col_idx].scatter(x[flags], g.loc[flags, "rz_sync"], color="#d62728", s=45, label="Flagged day")
        axes[1, col_idx].axhline(3.0, color="#f58518", linestyle="--", linewidth=1.4, label="Threshold +3")
        axes[1, col_idx].set_title(f"{treatment} | rz_sync", pad=10)
        axes[1, col_idx].set_ylabel("Robust z-score")
        axes[1, col_idx].set_xlabel("Date")

        for ax in [axes[0, col_idx], axes[1, col_idx]]:
            ax.xaxis.set_major_locator(mdates.DayLocator(interval=2))
            ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y-%m-%d"))
            ax.margins(x=0.03)
        axes[1, col_idx].tick_params(axis="x", rotation=28)

    legend_handles = [
        Line2D([0], [0], color="#1f77b4", marker="o", linewidth=1.8, label="rz_total"),
        Line2D([0], [0], color="#2ca02c", marker="s", linewidth=1.8, label="rz_sync"),
        Line2D([0], [0], color="#d62728", marker="o", linestyle="None", markersize=7, label="Flagged day"),
        Line2D([0], [0], color="#f58518", linestyle="--", linewidth=1.6, label="Threshold +3"),
    ]
    fig.legend(
        handles=legend_handles,
        loc="center left",
        ncol=1,
        bbox_to_anchor=(0.855, 0.5),
        frameon=True,
    )

    out = FIG_DIR / f"02_management_anomaly_rz_{year}.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


def plot_management_focus(anomaly: pd.DataFrame) -> str:
    """Plot focused evidence for High_shade in 2023 including user-observed date."""
    sub = anomaly[(anomaly["year"] == 2023) & (anomaly["treatment"] == "High_shade")].copy().sort_values("date")
    fig, ax1 = plt.subplots(figsize=(18, 7.2))
    fig.subplots_adjust(left=0.07, right=0.82, top=0.86, bottom=0.16)
    ax2 = ax1.twinx()

    ax1.plot(sub["date"], sub["day_total"], color="#4c78a8", marker="o", linewidth=2.0, label="day_total")
    ax2.plot(sub["date"], sub["sync_prop"], color="#f58518", marker="s", linewidth=2.0, label="sync_prop")

    flagged = sub[sub["management_anomaly"]]
    ax1.scatter(flagged["date"], flagged["day_total"], color="#d62728", s=60, zorder=5, label="Flagged day")

    target = pd.Timestamp("2023-03-02")
    ax1.axvline(target, color="#72b7b2", linestyle="--", linewidth=2.0)
    ax1.text(
        target,
        ax1.get_ylim()[1] * 0.96,
        "User-observed\n2023-03-02",
        color="#2f4b7c",
        fontsize=10,
        ha="left",
        va="top",
        bbox={"facecolor": "white", "alpha": 0.75, "edgecolor": "none", "pad": 1.8},
    )

    ax1.set_title("High_shade (2023): Daily total and synchronization evidence", pad=14)
    ax1.set_xlabel("Date")
    ax1.set_ylabel("day_total")
    ax2.set_ylabel("sync_prop")
    ax1.tick_params(axis="x", rotation=35)

    h1, l1 = ax1.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax1.legend(
        h1 + h2,
        l1 + l2,
        loc="lower right",
        ncol=1,
        frameon=True,
    )

    out = FIG_DIR / "03_management_focus_high_shade_2023.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


def plot_mating_rule_screening(pair_metrics: pd.DataFrame, params: Dict[str, float]) -> str:
    """Plot screening space of candidate metrics and thresholds."""
    x = pair_metrics.copy()
    cls = np.where(
        x["candidate_selected"],
        "selected",
        np.where(x["candidate_pre_cap"], "candidate_not_selected", "non_candidate"),
    )
    x["cls"] = cls

    # Downsample dense background for readability.
    non_cand = x[x["cls"] == "non_candidate"]
    if len(non_cand) > 2500:
        non_cand = non_cand.sample(2500, random_state=42)
    cand = x[x["cls"] != "non_candidate"]
    plot_df = pd.concat([non_cand, cand], ignore_index=True)

    fig, ax = plt.subplots(figsize=(10, 6))
    for c in ["non_candidate", "candidate_not_selected", "selected"]:
        g = plot_df[plot_df["cls"] == c]
        if g.empty:
            continue
        ax.scatter(
            g["count_z"],
            g["count_fc"],
            s=24 if c != "non_candidate" else 12,
            alpha=0.8 if c != "non_candidate" else 0.35,
            color=CLASS_COLORS[c],
            label=c,
            edgecolors="none",
        )

    ax.axvline(params["MATING_SCORE_THRESHOLD"], color="#f58518", linestyle="--", linewidth=1.8, label="score threshold")
    ax.axhline(params["MATING_FC_THRESHOLD"], color="#54a24b", linestyle="--", linewidth=1.8, label="fold-change threshold")

    ax.set_title("Day-level Screening Space: count_z vs count_fc")
    ax.set_xlabel("count_z")
    ax.set_ylabel("count_fc")
    ax.legend(loc="upper left", bbox_to_anchor=(1.01, 1.0), borderaxespad=0.0, frameon=True)

    fig.tight_layout()
    out = FIG_DIR / "04_mating_rule_screening.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


def plot_ram_distribution(ram_day: pd.DataFrame) -> str:
    """Plot ram daily partner distribution with visible mean markers."""
    fig, axes = plt.subplots(1, 2, figsize=(16, 5), constrained_layout=True)

    sns.boxplot(
        data=ram_day,
        x="treatment",
        y="mating_ewe_count",
        hue="year",
        palette=YEAR_COLORS,
        width=0.62,
        showfliers=False,
        ax=axes[0],
    )
    axes[0].set_title("Ram daily mating-partner count distribution")
    axes[0].set_xlabel("Treatment")
    axes[0].set_ylabel("Ewe partners per ram-day")
    axes[0].legend(title="Year", loc="upper left", bbox_to_anchor=(1.01, 1.0), borderaxespad=0.0, frameon=True)

    stats = (
        ram_day.groupby(["year", "treatment"], as_index=False)["mating_ewe_count"]
        .agg(["mean", "std", "count"])
        .reset_index()
    )
    stats = stats.rename(columns={"mean": "mean_count", "std": "std_count", "count": "n"})
    stats["sem"] = stats["std_count"] / np.sqrt(stats["n"].clip(lower=1))

    for year in YEARS:
        g = stats[stats["year"] == year].set_index("treatment").reindex(TREATMENT_ORDER).reset_index()
        axes[1].errorbar(
            g["treatment"],
            g["mean_count"],
            yerr=g["sem"],
            marker="o",
            markersize=7,
            linewidth=2.2,
            capsize=4,
            color=YEAR_COLORS[year],
            label=str(year),
        )

    axes[1].set_title("Ram partner mean ± SEM (clear year contrast)")
    axes[1].set_xlabel("Treatment")
    axes[1].set_ylabel("Mean ewe partners per ram-day")
    axes[1].legend(title="Year", loc="upper left", bbox_to_anchor=(1.01, 1.0), borderaxespad=0.0, frameon=True)

    out = FIG_DIR / "05_ram_daily_partner_distribution.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


def plot_ewe_profile(ewe_summary: pd.DataFrame) -> str:
    """Plot ewe-level mating count and partner diversity."""
    fig, axes = plt.subplots(1, 2, figsize=(16, 5), constrained_layout=True)

    bins = np.arange(0.5, max(4, int(ewe_summary["mating_count"].max())) + 1.5, 1)
    for year in YEARS:
        g = ewe_summary[ewe_summary["year"] == year]
        axes[0].hist(
            g["mating_count"],
            bins=bins,
            alpha=0.6,
            color=YEAR_COLORS[year],
            label=str(year),
            edgecolor="white",
        )
    axes[0].set_title("Ewe inferred mating-count distribution")
    axes[0].set_xlabel("Mating count per ewe")
    axes[0].set_ylabel("Ewe count")
    axes[0].legend(title="Year", loc="upper right", frameon=True)

    ewe_box = ewe_summary.copy()
    ewe_box["year_str"] = ewe_box["year"].astype(str)
    year_palette_str = {str(k): v for k, v in YEAR_COLORS.items()}
    sns.boxplot(
        data=ewe_box,
        x="year_str",
        y="unique_rams",
        hue="year_str",
        palette=year_palette_str,
        ax=axes[1],
        showfliers=False,
    )
    if axes[1].legend_ is not None:
        axes[1].legend_.remove()
    axes[1].set_title("Ewe partner diversity (unique rams)")
    axes[1].set_xlabel("Year")
    axes[1].set_ylabel("Unique ram count")

    out = FIG_DIR / "06_ewe_mating_profile.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


def _ordered_time_zones(zones: List[str]) -> List[str]:
    """Sort time-zone strings by start hour."""
    def key(z: str) -> int:
        try:
            return int(str(z).split(":")[0])
        except Exception:
            return 99

    return sorted(set(zones), key=key)


def plot_time_zone_preference(tz_summary: pd.DataFrame) -> str:
    """Plot time-zone preference with external legend."""
    zone_order = _ordered_time_zones(tz_summary["time_zone"].dropna().tolist())
    palette = sns.color_palette("Set2", n_colors=max(3, len(zone_order)))
    zone_colors = {z: palette[i] for i, z in enumerate(zone_order)}

    fig, axes = plt.subplots(1, 2, figsize=(19, 7), sharey=True)
    fig.subplots_adjust(top=0.84, bottom=0.20, left=0.06, right=0.985, wspace=0.02)
    for idx, year in enumerate(YEARS):
        sub = tz_summary[tz_summary["year"] == year]
        pivot = (
            sub.pivot(index="treatment", columns="time_zone", values="mating_events")
            .reindex(index=TREATMENT_ORDER, columns=zone_order)
            .fillna(0)
        )

        bottom = np.zeros(len(pivot))
        for zone in zone_order:
            vals = pivot[zone].to_numpy()
            axes[idx].bar(
                pivot.index,
                vals,
                bottom=bottom,
                color=zone_colors[zone],
                label=zone,
                edgecolor="white",
            )
            bottom += vals

        axes[idx].set_title(f"{year} time-zone preference by treatment", pad=10)
        axes[idx].set_xlabel("Treatment")
        if idx == 0:
            axes[idx].set_ylabel("Mating events")

    handles = [plt.Rectangle((0, 0), 1, 1, color=zone_colors[z]) for z in zone_order]
    fig.legend(
        handles,
        zone_order,
        loc="upper center",
        ncol=min(6, len(zone_order)),
        bbox_to_anchor=(0.5, 0.985),
        frameon=True,
    )

    out = FIG_DIR / "07_time_zone_preference.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


def plot_mating_events_by_group(split_index: pd.DataFrame) -> str:
    """Plot event count by year and treatment."""
    fig, ax = plt.subplots(figsize=(9, 5))
    sns.barplot(
        data=split_index,
        x="treatment",
        y="mating_Y",
        hue="year",
        palette=YEAR_COLORS,
        ax=ax,
    )
    ax.set_title("Inferred mating events by treatment and year")
    ax.set_xlabel("Treatment")
    ax.set_ylabel("Mating events (Mating=Y)")
    ax.legend(title="Year", loc="upper left", bbox_to_anchor=(1.01, 1.0), borderaxespad=0.0, frameon=True)
    fig.tight_layout()
    out = FIG_DIR / "08_mating_events_by_group.png"
    save_figure(fig, out)
    plt.close(fig)
    return out.name


# -----------------------------
# Report generation
# -----------------------------

def anomaly_day_summary(anomaly: pd.DataFrame) -> pd.DataFrame:
    """Return only flagged anomaly days for report tables."""
    cols = ["year", "treatment", "date", "day_total", "sync_prop", "rz_total", "rz_sync"]
    out = anomaly[anomaly["management_anomaly"]][cols].copy()
    out["date"] = out["date"].dt.date.astype(str)
    out = out.sort_values(["year", "treatment", "date"]).reset_index(drop=True)
    return out


def top_ram_insights(final_results: pd.DataFrame) -> pd.DataFrame:
    """Build top-ram insight table."""
    y = final_results[final_results["is_mating"]].copy()
    y["date_str"] = y["date"].dt.date.astype(str)
    ram = (
        y.groupby(["year", "treatment", "Ram_EID"], as_index=False)
        .agg(
            mating_events=("Mating", "count"),
            active_days=("date_str", "nunique"),
            unique_ewes=("Ewe_EID", "nunique"),
            mean_day_count=("day_proximity_times", "mean"),
        )
        .sort_values(["year", "mating_events", "active_days"], ascending=[True, False, False])
    )
    return ram


def build_time_zone_peak_table(tz_summary: pd.DataFrame) -> pd.DataFrame:
    """For each year-treatment group, find top time-zone and share."""
    rows: List[dict] = []
    for (year, treatment), g in tz_summary.groupby(["year", "treatment"]):
        total = g["mating_events"].sum()
        top = g.sort_values("mating_events", ascending=False).iloc[0]
        rows.append(
            {
                "year": int(year),
                "treatment": treatment,
                "top_time_zone": top["time_zone"],
                "top_events": int(top["mating_events"]),
                "top_share": float(top["mating_events"] / total) if total > 0 else 0.0,
            }
        )
    return pd.DataFrame(rows).sort_values(["year", "treatment"]).reset_index(drop=True)


def write_cn_report(
    tables: Dict[str, pd.DataFrame],
    params: Dict[str, float],
    fig_names: Dict[str, str],
) -> None:
    """Write Chinese report with embedded evidence and interpretations."""
    prefilter_audit = tables["prefilter_audit"]
    pair_metrics = tables["pair_metrics"]
    pair_event_summary = tables["pair_event_summary"]
    anomaly = tables["anomaly"]
    split_index = tables["split_index"]
    final_results = tables["final_results"]
    ewe_summary = tables["ewe_summary"]
    tz_summary = tables["tz_summary"]

    total_pairs_raw = int(len(prefilter_audit))
    removed_step2 = int((~prefilter_audit["pass_step2_non_zero_days"]).sum())
    removed_step4 = int((prefilter_audit["pass_step2_non_zero_days"] & (~prefilter_audit["pass_step4_robust_z"])).sum())
    kept_pairs = int(prefilter_audit["pair_prefilter_keep"].sum())

    evaluated_pair_days = int(len(pair_metrics))
    candidates_pre_cap = int(pair_metrics["candidate_pre_cap"].sum())
    selected_events = int(pair_metrics["candidate_selected"].sum())
    removed_by_cap = int(pair_metrics["candidate_removed_by_cap"].sum())
    pairs_with_candidate_days = int((pair_event_summary["candidate_days_pre_cap"] > 0).sum())
    pairs_with_selected_days = int((pair_event_summary["candidate_days_selected"] > 0).sum())
    selected_days_per_selected_pair = (
        float(selected_events) / float(pairs_with_selected_days) if pairs_with_selected_days > 0 else 0.0
    )

    flagged = anomaly_day_summary(anomaly)
    flagged_day_count = int(anomaly["management_anomaly"].sum())
    peak_tz = build_time_zone_peak_table(tz_summary)

    ram_rank = top_ram_insights(final_results)
    ram_top10 = ram_rank.head(10)

    ewe_over3 = int((ewe_summary["mating_count"] > 3).sum())
    ewe_total = int(len(ewe_summary))
    ewe_multi_ram = int((ewe_summary["unique_rams"] >= 2).sum())

    group_table = split_index[["year", "treatment", "rows", "mating_Y"]].copy()
    group_table["mating_rate"] = (group_table["mating_Y"] / group_table["rows"] * 100).round(2)
    pair_multi_day = (
        pair_event_summary[pair_event_summary["candidate_days_selected"] >= 2]
        .sort_values(["candidate_days_selected", "candidate_days_pre_cap"], ascending=False)
        .head(10)[["year", "treatment", "Ewe_EID", "Ram_EID", "candidate_days_selected", "candidate_days_pre_cap"]]
    )
    if pair_multi_day.empty:
        pair_multi_day_text = "无（当前阈值下未出现同一pair有2天及以上被最终保留）。"
    else:
        pair_multi_day_text = df_to_markdown(pair_multi_day, max_rows=10)

    # Physical meaning details for synchronization.
    sync_formula = (
        "sync_prop(d) = 该日中满足 x(pair,d) > q90(pair) 的pair数 / 该treatment总pair数"
    )

    cn = f"""# UWA公羊母羊交配识别分析报告（中文，升级版）

## 1. 目标与本报告范围
本报告严格基于当前代码逻辑，解释：
- pair级数据过滤为什么必要、如何执行；
- 牧场管理异常日如何识别，以及其物理含义；
- 交配判定规则如何从统计和生物学约束共同构建；
- 公羊/母羊维度结论、时间段偏好与可视化证据。

## 2. 流程总览（与代码一致）
1. 运行 `02_eda_uwa_mating_analysis.py`：完成 pair预过滤、管理异常日识别、交配事件判定、结果/表格输出。
2. 运行 `03_eda_report_generation.py`：从 `data/uwa_proximity_eda/tables/` 读取结果，生成图与中英文报告。

## 3. 异常处理逻辑（代码一致）
### 3.1 Pair级数据过滤（先做，再做其他分析）
- Step 1: 统计每个pair非零实验天数。
- Step 2: 过滤 `non_zero_days < {int(params['PAIR_MIN_NONZERO_DAYS'])}`。
- Step 3: 对剩余pair，只取非零值，去掉两个最大和两个最小，求trimmed mean。
- Step 4: 在 `year+treatment` 内对 trimmed mean 做 robust z-score，过滤 `|rz| > {fmt_num(params['PAIR_RZ_THRESHOLD'])}`。

本次数据结果：
- 原始pair数：**{total_pairs_raw}**
- Step 2 去除：**{removed_step2}**（{fmt_pct(removed_step2, total_pairs_raw)}）
- Step 4 去除：**{removed_step4}**（{fmt_pct(removed_step4, total_pairs_raw)}）
- 保留：**{kept_pairs}**（{fmt_pct(kept_pairs, total_pairs_raw)}）

物理解释（推断，非直接观测）：
- 非零天数很少（<7）说明该pair在绝大多数天没有稳定接近，更像偶发信号；
- trimmed mean异常（|rz|>3）说明其信号形态偏离同组主体，常见原因之一是边界区域信号穿透或短时群聚造成的“伪接近”；
- 对紧邻paddock（如High/Medium相邻）而言，这类过滤可显著降低跨围栏串联噪声风险。

![Pair过滤证据](../figures/{fig_names['prefilter']})

### 3.2 牧场管理异常日识别：不仅看“总量高”，还看“是否群体同步”
每天、每个treatment计算两个指标：
- `day_total`：当天所有pair接近次数总和。
- `sync_prop`：{sync_formula}

其中 `q90(pair)` 是该pair在整个实验窗口内的90分位。

为什么 `sync_prop` 很关键：
- 如果只是少数pair冲高，可能是个体行为（潜在交配线索）；
- 如果大量pair同一天同时超过各自高位阈值，更像管理活动（投喂、驱赶、集中休息）引起的群体同步。

判定规则：
- `rz_total >= {fmt_num(params['MANAGEMENT_RZ_THRESHOLD'])}` 或 `rz_sync >= {fmt_num(params['MANAGEMENT_RZ_THRESHOLD'])}` 即标记为管理异常日。

异常日表（已标记）：
{df_to_markdown(flagged, max_rows=20)}

![管理异常日证据-2023](../figures/{fig_names['anomaly_2023']})
![管理异常日证据-2024](../figures/{fig_names['anomaly_2024']})
![High_shade 2023焦点图](../figures/{fig_names['focus']})

### 3.3 Pair-day候选生成（全非零日扫描）
当前逻辑不再做 `low_signal` 二次过滤，而是直接对每个pair的每一个非零日做判定：
- 基线仅使用“非管理异常日”中的非零值（`BASELINE_NONZERO_ONLY={int(params['BASELINE_NONZERO_ONLY'])}`）；
- 遍历所有非零天（`SCAN_ALL_NONZERO_DAYS={int(params['SCAN_ALL_NONZERO_DAYS'])}`），逐日计算：
  `count_z = (count_value - baseline_median_nonzero) / (1.4826 * baseline_mad_nonzero + 1)`  
  `count_fc = (count_value + 1) / (baseline_median_nonzero + 1)`
- 若该日是管理异常日，则直接排除，不作为交配候选。

当前结果：
- 被评估的非零pair-day：**{evaluated_pair_days}**
- 产生候选的pair-day（cap前）：**{candidates_pre_cap}**
- 生物学cap后保留的pair-day（Mating=Y）：**{selected_events}**
- 被cap移除的候选pair-day：**{removed_by_cap}**
- 至少出现1个候选日的pair数：**{pairs_with_candidate_days}**
- 至少出现1个保留交配日的pair数：**{pairs_with_selected_days}**
- 每个“有交配”的pair平均保留天数：**{selected_days_per_selected_pair:.2f}**

## 4. 交配判定规则及其依据
对每个pair-day（非管理异常日）独立判定，需同时满足：
- `count_value >= {fmt_num(params['MATING_ABS_COUNT_THRESHOLD'])}`
- `count_z >= {fmt_num(params['MATING_SCORE_THRESHOLD'])}`
- `count_fc >= {fmt_num(params['MATING_FC_THRESHOLD'])}`

含义：
- `count_z` 保证该日显著偏离pair自身常态；
- `count_fc` 保证对基线具备足够倍数提升；
- `count_value` 保证绝对强度足够大，不被低幅噪声触发。

说明：当前版本已去掉 `best_day_dominance`，因此同一pair允许在不同天被同时识别为潜在交配事件，更符合“同一发情周期内可能存在多次高峰接近”的实际场景。

随后施加生物学约束：
- 每只公羊每天最多保留 `{int(params['MAX_EWE_PER_RAM_PER_DAY'])}` 个母羊候选；
- 每只母羊每天最多保留 `{int(params['MAX_RAM_PER_EWE_PER_DAY'])}` 个公羊候选。

![交配判定筛选空间](../figures/{fig_names['screening']})

## 5. 结果概览（按年份与treatment）
{df_to_markdown(group_table, max_rows=20)}

![分组交配事件数](../figures/{fig_names['group_events']})

管理异常日数量：**{flagged_day_count}**。这些日期已从交配候选判定中排除。

同一pair多日被保留（前10）：
{pair_multi_day_text}

## 6. 公羊维度发现（结论+解释）
- Top公羊（按推断交配事件数）显示明显个体差异，少数公羊承担更高的交配负载。
- 从 `ram_day` 看，日内配对数分布在不同treatment和年份存在偏移，提示环境条件会影响接近行为强度。

Top 10 公羊（跨组排序）：
{df_to_markdown(ram_top10[["year", "treatment", "Ram_EID", "mating_events", "active_days", "unique_ewes"]], max_rows=10)}

![公羊日内配对分布](../figures/{fig_names['ram']})

## 7. 母羊维度发现（结论+解释）
- 母羊推断交配次数 >3 的个体：**{ewe_over3}/{ewe_total}**（{fmt_pct(ewe_over3, ewe_total)}）。
- 与2只及以上公羊发生关系的母羊：**{ewe_multi_ram}/{ewe_total}**（{fmt_pct(ewe_multi_ram, ewe_total)}）。
- 这部分个体建议回到原始5分钟数据复核，确认是否存在群聚或边界噪声影响。

![母羊交配画像](../figures/{fig_names['ewe']})

## 8. 时间段偏好与行为解释
每个 `year+treatment` 的首选time-zone如下：
{df_to_markdown(peak_tz, max_rows=20)}

解释：
- time-zone偏好通常与温热环境、管理作业节律、群体活动峰值相关；
- 该指标用于定位“更可能发生交配的时段”，便于后续对视频/现场记录做定向核查。

![时间段偏好](../figures/{fig_names['tz']})

## 9. 理论与外部支持（文献/资料）
1. Robust z-score使用MAD（中位数绝对偏差）作为稳健尺度，常用于异常值检测：
   - SciPy `median_abs_deviation` 文档: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_abs_deviation.html
2. MAD稳健尺度理论来源：
   - Rousseeuw PJ, Croux C (1993), *Alternatives to the Median Absolute Deviation*, JASA. DOI: https://doi.org/10.1080/01621459.1993.10476408
3. 羊发情/配种窗口的生理背景（用于解释“短窗主峰”思路）：
   - Merck Veterinary Manual, Estrus in Ewes: https://www.merckvetmanual.com/management-and-nutrition/management-of-reproduction-sheep/estrus-in-ewes
4. 近距离传感器可识别繁殖相关事件，且管理活动会改变接近模式：
   - Animal Biotelemetry (2024): https://animalbiotelemetry.biomedcentral.com/articles/10.1186/s40317-024-00388-x
   - Animal Biotelemetry (2020): https://doi.org/10.1186/s40317-020-00214-6

## 10. 输出位置
- 报告（中文）：`data/uwa_proximity_eda/reports/uwa_proximity_eda_cn.md`
- 报告（英文）：`data/uwa_proximity_eda/reports/uwa_proximity_eda_en.md`
- 图：`data/uwa_proximity_eda/figures/`
- 证据表：`data/uwa_proximity_eda/tables/`
- 最终结果：`data/uwa_proximity_res/`（6个文件）
"""

    (REPORT_DIR / "uwa_proximity_eda_cn.md").write_text(cn, encoding="utf-8")


def write_en_report(
    tables: Dict[str, pd.DataFrame],
    params: Dict[str, float],
    fig_names: Dict[str, str],
) -> None:
    """Write English report with embedded evidence and interpretations."""
    prefilter_audit = tables["prefilter_audit"]
    pair_metrics = tables["pair_metrics"]
    pair_event_summary = tables["pair_event_summary"]
    anomaly = tables["anomaly"]
    split_index = tables["split_index"]
    final_results = tables["final_results"]
    ewe_summary = tables["ewe_summary"]
    tz_summary = tables["tz_summary"]

    total_pairs_raw = int(len(prefilter_audit))
    removed_step2 = int((~prefilter_audit["pass_step2_non_zero_days"]).sum())
    removed_step4 = int((prefilter_audit["pass_step2_non_zero_days"] & (~prefilter_audit["pass_step4_robust_z"])).sum())
    kept_pairs = int(prefilter_audit["pair_prefilter_keep"].sum())

    evaluated_pair_days = int(len(pair_metrics))
    candidates_pre_cap = int(pair_metrics["candidate_pre_cap"].sum())
    selected_events = int(pair_metrics["candidate_selected"].sum())
    removed_by_cap = int(pair_metrics["candidate_removed_by_cap"].sum())
    pairs_with_candidate_days = int((pair_event_summary["candidate_days_pre_cap"] > 0).sum())
    pairs_with_selected_days = int((pair_event_summary["candidate_days_selected"] > 0).sum())
    selected_days_per_selected_pair = (
        float(selected_events) / float(pairs_with_selected_days) if pairs_with_selected_days > 0 else 0.0
    )

    flagged = anomaly_day_summary(anomaly)
    flagged_day_count = int(anomaly["management_anomaly"].sum())
    peak_tz = build_time_zone_peak_table(tz_summary)

    ram_rank = top_ram_insights(final_results)
    ram_top10 = ram_rank.head(10)

    ewe_over3 = int((ewe_summary["mating_count"] > 3).sum())
    ewe_total = int(len(ewe_summary))
    ewe_multi_ram = int((ewe_summary["unique_rams"] >= 2).sum())

    group_table = split_index[["year", "treatment", "rows", "mating_Y"]].copy()
    group_table["mating_rate"] = (group_table["mating_Y"] / group_table["rows"] * 100).round(2)
    pair_multi_day = (
        pair_event_summary[pair_event_summary["candidate_days_selected"] >= 2]
        .sort_values(["candidate_days_selected", "candidate_days_pre_cap"], ascending=False)
        .head(10)[["year", "treatment", "Ewe_EID", "Ram_EID", "candidate_days_selected", "candidate_days_pre_cap"]]
    )
    if pair_multi_day.empty:
        pair_multi_day_text = "No pair has >=2 selected candidate days under current thresholds."
    else:
        pair_multi_day_text = df_to_markdown(pair_multi_day, max_rows=10)

    sync_formula = "sync_prop(d) = (#pairs with x(pair,d) > q90(pair)) / (total pairs in that treatment)"

    en = f"""# UWA Ram-Ewe Mating Inference Report (Enhanced, English)

## 1. Scope and objective
This report is regenerated from the **actual implemented logic** and explains:
- why pair-level filtering is required,
- how management anomaly days are detected (with physical meaning),
- how mating rules combine statistics and biological constraints,
- what conclusions are supported at ram/ewe/time-zone levels.

## 2. Pipeline separation
1. `02_eda_uwa_mating_analysis.py`: data filtering, anomaly detection, mating inference, tables/results.
2. `03_eda_report_generation.py`: visualization and bilingual report generation.

## 3. Anomaly handling logic (code-aligned)
### 3.1 Pair pre-filtering first
- Step 1: count non-zero experiment days per pair.
- Step 2: remove pairs with `non_zero_days < {int(params['PAIR_MIN_NONZERO_DAYS'])}`.
- Step 3: compute non-zero trimmed mean after dropping 2 max + 2 min values.
- Step 4: within each `year+treatment`, remove pairs with `|robust_z(trimmed_mean)| > {fmt_num(params['PAIR_RZ_THRESHOLD'])}`.

Observed counts:
- Raw pairs: **{total_pairs_raw}**
- Removed in Step 2: **{removed_step2}** ({fmt_pct(removed_step2, total_pairs_raw)})
- Removed in Step 4: **{removed_step4}** ({fmt_pct(removed_step4, total_pairs_raw)})
- Kept: **{kept_pairs}** ({fmt_pct(kept_pairs, total_pairs_raw)})

Physical interpretation (inference):
- very low non-zero-day pairs are unlikely to represent stable social/reproductive proximity,
- extreme trimmed-mean outliers often indicate geometric boundary effects or short group-cluster artifacts,
- this is especially relevant for adjacent paddocks where cross-boundary sensor bleed can occur.

![Pair pre-filter evidence](../figures/{fig_names['prefilter']})

### 3.2 Management anomaly days: intensity + synchronization
For each `year+treatment+day`, two metrics are used:
- `day_total`: total proximity counts of all pairs,
- `sync_prop`: {sync_formula}

Why `sync_prop` matters:
- high `day_total` alone can be driven by a few pairs,
- high `sync_prop` indicates many pairs peaking simultaneously, which is more consistent with management-driven aggregation than pair-specific mating.

Decision rule:
- day is flagged if `rz_total >= {fmt_num(params['MANAGEMENT_RZ_THRESHOLD'])}` OR `rz_sync >= {fmt_num(params['MANAGEMENT_RZ_THRESHOLD'])}`.

Flagged days:
{df_to_markdown(flagged, max_rows=20)}

![Management anomaly evidence 2023](../figures/{fig_names['anomaly_2023']})
![Management anomaly evidence 2024](../figures/{fig_names['anomaly_2024']})
![High_shade 2023 focus](../figures/{fig_names['focus']})

### 3.3 Pair-day candidate generation (scan all non-zero days)
The current logic no longer applies a second `low_signal` filter.  
Instead, every non-zero day of every pair is screened:
- baseline uses non-zero values only on non-management-anomaly days (`BASELINE_NONZERO_ONLY={int(params['BASELINE_NONZERO_ONLY'])}`),
- all non-zero days are evaluated (`SCAN_ALL_NONZERO_DAYS={int(params['SCAN_ALL_NONZERO_DAYS'])}`),
- day-level metrics:
  `count_z = (count_value - baseline_median_nonzero) / (1.4826 * baseline_mad_nonzero + 1)`  
  `count_fc = (count_value + 1) / (baseline_median_nonzero + 1)`,
- days flagged as management anomalies are excluded before candidate labeling.

Current counts:
- Evaluated non-zero pair-days: **{evaluated_pair_days}**
- Candidate pair-days before biological caps: **{candidates_pre_cap}**
- Selected pair-days after caps (`Mating=Y`): **{selected_events}**
- Candidate pair-days removed by caps: **{removed_by_cap}**
- Pairs with >=1 candidate day: **{pairs_with_candidate_days}**
- Pairs with >=1 selected day: **{pairs_with_selected_days}**
- Mean selected days per selected pair: **{selected_days_per_selected_pair:.2f}**

## 4. Mating decision rules and rationale
Each pair-day (excluding management-anomaly days) must satisfy all thresholds:
- `count_value >= {fmt_num(params['MATING_ABS_COUNT_THRESHOLD'])}`
- `count_z >= {fmt_num(params['MATING_SCORE_THRESHOLD'])}`
- `count_fc >= {fmt_num(params['MATING_FC_THRESHOLD'])}`

Interpretation:
- robust score enforces statistically abnormal elevation vs the pair's own baseline,
- fold-change enforces practical effect size above baseline,
- absolute count blocks low-amplitude noise.

Note: `best_day_dominance` is intentionally removed in this version, so one pair can keep multiple mating days if multiple days independently pass all thresholds.

Biological caps:
- max `{int(params['MAX_EWE_PER_RAM_PER_DAY'])}` ewes per `ram+day`,
- max `{int(params['MAX_RAM_PER_EWE_PER_DAY'])}` rams per `ewe+day`.

![Mating rule screening](../figures/{fig_names['screening']})

## 5. Group-level outcomes
{df_to_markdown(group_table, max_rows=20)}

![Events by year-treatment](../figures/{fig_names['group_events']})

Flagged management anomaly days: **{flagged_day_count}**.  
These days are excluded from pair-day mating candidacy.

Top pairs with multi-day selected events:
{pair_multi_day_text}

## 6. Ram-level findings (with interpretation)
- mating load is concentrated in a subset of rams,
- treatment/year conditions shift the daily partner-count distribution.

Top 10 rams:
{df_to_markdown(ram_top10[["year", "treatment", "Ram_EID", "mating_events", "active_days", "unique_ewes"]], max_rows=10)}

![Ram distribution](../figures/{fig_names['ram']})

## 7. Ewe-level findings (with interpretation)
- ewes with >3 inferred mating events: **{ewe_over3}/{ewe_total}** ({fmt_pct(ewe_over3, ewe_total)}),
- ewes with >=2 ram partners: **{ewe_multi_ram}/{ewe_total}** ({fmt_pct(ewe_multi_ram, ewe_total)}).

These cases should be prioritized for raw 5-minute trace validation.

![Ewe profile](../figures/{fig_names['ewe']})

## 8. Time-zone preference
Top zone by `year+treatment`:
{df_to_markdown(peak_tz, max_rows=20)}

Interpretation:
- time-zone peaks help locate likely mating windows,
- and can guide targeted validation against field logs/video.

![Time-zone preference](../figures/{fig_names['tz']})

## 9. External references
1. SciPy MAD documentation (robust scale):
   - https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_abs_deviation.html
2. Robust scale estimator theory:
   - Rousseeuw PJ, Croux C (1993), DOI: https://doi.org/10.1080/01621459.1993.10476408
3. Ewe estrus physiology reference:
   - Merck Veterinary Manual: https://www.merckvetmanual.com/management-and-nutrition/management-of-reproduction-sheep/estrus-in-ewes
4. Proximity sensors and management-context effects:
   - Animal Biotelemetry 2024: https://animalbiotelemetry.biomedcentral.com/articles/10.1186/s40317-024-00388-x
   - Animal Biotelemetry 2020: https://doi.org/10.1186/s40317-020-00214-6

## 10. Output locations
- Chinese report: `data/uwa_proximity_eda/reports/uwa_proximity_eda_cn.md`
- English report: `data/uwa_proximity_eda/reports/uwa_proximity_eda_en.md`
- Figures: `data/uwa_proximity_eda/figures/`
- Tables: `data/uwa_proximity_eda/tables/`
- Final 6 result files: `data/uwa_proximity_res/`
"""

    (REPORT_DIR / "uwa_proximity_eda_en.md").write_text(en, encoding="utf-8")


def main() -> None:
    """Run report generation."""
    ensure_dirs()

    sns.set_theme(style="whitegrid", context="talk")
    plt.rcParams["figure.dpi"] = 150
    plt.rcParams["savefig.dpi"] = 200

    tables = require_tables()
    preprocess_tables(tables)
    params = param_map(tables["parameters"])

    fig_names = {
        "prefilter": plot_prefilter_evidence(tables["prefilter_audit"], tables["prefilter_summary"], params),
        "anomaly_2023": _plot_year_anomaly_panel(tables["anomaly"], 2023),
        "anomaly_2024": _plot_year_anomaly_panel(tables["anomaly"], 2024),
        "focus": plot_management_focus(tables["anomaly"]),
        "screening": plot_mating_rule_screening(tables["pair_metrics"], params),
        "ram": plot_ram_distribution(tables["ram_day"]),
        "ewe": plot_ewe_profile(tables["ewe_summary"]),
        "tz": plot_time_zone_preference(tables["tz_summary"]),
        "group_events": plot_mating_events_by_group(tables["split_index"]),
    }

    write_cn_report(tables, params, fig_names)
    write_en_report(tables, params, fig_names)

    print("Saved report figures:")
    for key, name in fig_names.items():
        print(f"- {key}: {FIG_DIR / name}")
    print("Saved reports:")
    print(f"- {REPORT_DIR / 'uwa_proximity_eda_cn.md'}")
    print(f"- {REPORT_DIR / 'uwa_proximity_eda_en.md'}")


if __name__ == "__main__":
    main()
